name: "Lint and Tests"

on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - ml_frameworks_bot/**

jobs:
  lint-and-test:
    name: "Lint using ruff and run test suite"

    runs-on: ubuntu-latest

    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "pyproject.toml"

      - name: Set up Python 3.10
        run: uv python install 3.10

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: ruff format
        run: |
          uv run ruff check ml_frameworks_bot

      - name: Test with PyTest
        run: |
          uv run pytest -s -v .
