name: Tests
on:
  pull_request:
    paths:
      - .github/workflows/tests.yml
      - ml_frameworks_bot/**
      - requirements.txt
      - setup.py

jobs:
  code-format:
    name: check code format using black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
  lint:
    name: Check linting using ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          pip install -U pip pytest
          pip install .
          pytest -s .